Document: dionaea-nisl
Title: Debian dionaea-nisl Manual
Author: <insert document author here>
Abstract: This manual describes what dionaea-nisl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dionaea-nisl/dionaea-nisl.sgml.gz

Format: postscript
Files: /usr/share/doc/dionaea-nisl/dionaea-nisl.ps.gz

Format: text
Files: /usr/share/doc/dionaea-nisl/dionaea-nisl.text.gz

Format: HTML
Index: /usr/share/doc/dionaea-nisl/html/index.html
Files: /usr/share/doc/dionaea-nisl/html/*.html
